Repository fga-eps-mds/2020.2-CheeryUP, pull requests merged in 2021-05, with the labels that each got.

#148 129/cadastra consulta
  src/CheerUp/urls.py
  src/paciente/migrations/0003_consulta.py
  src/paciente/migrations/0004_auto_20210501_0234.py
  src/paciente/models.py
  src/paciente/serializers.py
  src/paciente/views.py
Labels: Sprint 12, backend, pull request

#151 150/documentar api
  src/CheerUp/settings.py
  src/CheerUp/urls.py
  src/paciente/serializers.py
  src/requirements.txt
  src/users/urls.py
Labels: backend, pull request

#152 Feature/auth login
  src/CheerUp/settings.py
  src/CheerUp/urls.py
  src/paciente/models.py
  src/paciente/serializers.py
  src/paciente/views.py
  src/users/serializers.py
  src/users/urls.py
  src/users/views.py
Labels: backend, frontend, pull request

#157 Sync
  src/CheerUp/settings.py
  src/CheerUp/urls.py
  src/paciente/migrations/0001_initial.py
  src/paciente/migrations/0002_auto_20210419_1825.py
  src/paciente/migrations/0002_consulta_produtividade.py
  src/paciente/migrations/0003_consulta.py
  src/paciente/migrations/0004_auto_20210501_0234.py
  src/paciente/models.py
  src/paciente/serializers.py
  src/paciente/views.py
  src/users/migrations/0002_psicologo_name.py
  src/users/models.py
  src/users/serializers.py
  src/users/urls.py
  src/users/views.py
Labels: Sync, pull request

#159 Swagger
  src/CheerUp/settings.py
  src/CheerUp/urls.py
  src/requirements.txt
Labels: bug, pull request

#160 Development
  src/CheerUp/settings.py
  src/CheerUp/urls.py
  src/requirements.txt
Labels: Sync

#169 add_tests_95% #163
  src/paciente/serializers.py
  src/paciente/tests/test_views.py
  src/users/serializers.py
  src/users/urls.py
Labels: Testes, pull request

#172 163/testes
  src/paciente/tests/test_views.py
  src/users/tests/test_views.py
Labels: Testes, pull request

#173 Development
  docs/Roadmaps/roadmap_geral.md
  src/cov.xml
  src/paciente/tests/test_views.py
  src/users/tests/test_views.py
Labels: Sync, pull request

#174 Sync
  src/CheerUp/settings.py
Labels: Sync, pull request

#178 161/postmodern
  docs/wiki/postmortem.md
Labels: documentation, pull request

#179 Update/test users
  src/users/serializers.py
  src/users/tests/test_views.py
Labels: Sprint 13, backend, bug, pull request

#180 Development
  src/.coveragerc
  src/cov.xml
  src/users/serializers.py
  src/users/tests/test_views.py
Labels: Sync, pull request

#181 Better code
  src/CheerUp/delete_later.md
  src/CheerUp/urls.py
  src/paciente/urls.py
  src/paciente/views.py
  src/users/tests/test_views.py
  src/users/urls.py
  src/users/views.py
Labels: RETA FINAL, Sprint 13, enhancement, pull request

#182 Sync
  src/CheerUp/delete_later.md
  src/CheerUp/urls.py
  src/paciente/urls.py
  src/paciente/views.py
  src/users/tests/test_views.py
  src/users/urls.py
  src/users/views.py
Labels: Sync, pull request
