Repository fga-eps-mds/2020.2-CheeryUP, pull requests merged in 2021-04, with the labels that each got.

#94 bugs_correcao de registro de psicologo #93
  src/paciente/__pycache__/__init__.cpython-39.pyc
  src/paciente/__pycache__/admin.cpython-39.pyc
  src/paciente/__pycache__/models.cpython-39.pyc
  src/paciente/__pycache__/serializers.cpython-39.pyc
  src/paciente/__pycache__/views.cpython-39.pyc
  src/paciente/migrations/0001_initial.py
  src/paciente/migrations/__pycache__/0001_initial.cpython-39.pyc
  src/paciente/migrations/__pycache__/__init__.cpython-39.pyc
  src/users/__pycache__/__init__.cpython-39.pyc
  src/users/__pycache__/admin.cpython-39.pyc
  src/users/__pycache__/models.cpython-39.pyc
  src/users/__pycache__/serializers.cpython-39.pyc
  src/users/__pycache__/urls.cpython-39.pyc
  src/users/__pycache__/views.cpython-39.pyc
  src/users/migrations/0001_initial.py
  src/users/migrations/0002_auto_20210328_1430.py
  src/users/migrations/__pycache__/0001_initial.cpython-39.pyc
  src/users/migrations/__pycache__/0002_auto_20210320_0214.cpython-39.pyc
  src/users/migrations/__pycache__/__init__.cpython-39.pyc
  src/users/models.py
  src/users/serializers.py
Labels: Atualização, Sprint 8, bug, pull request, urgent

#95 feat_login_e_autenticação do psicologo #74
  requirements.txt
  src/CheerUp/settings.py
  src/CheerUp/urls.py
  src/users/urls.py
  src/users/views.py
Labels: DevOps, Sprint 8, backend, pull request, user-story

#104 docs_att_RefatoraçãoCanvas #97
  docs/assets/images/canvas.png
  docs/wiki/Canvas.md
Labels: Atualização, Sprint 9, documentation, pull request

#105 Git flow
  CONTRIBUTING.md
  docs/wiki/PolíticasdeContribuiçao.md
Labels: ScrumMaster, Sprint 9

#106 101/doc arquitetura
  docs/wiki/Documentos/Documento_de_Arquitetura.md
Labels: Arquitetura, Atualização, Sprint 9, documentation, pull request

#118 103/testes unitarios
  .envs/.postgres
  .vscode/settings.json
  Dockerfile
  docker-compose.yml
  src/CheerUp/settings.py
  src/CheerUp/urls.py
  src/paciente/migrations/0001_initial.py
  src/paciente/models.py
  src/paciente/serializers.py
  src/paciente/urls.py
  src/paciente/views.py
  src/requirements.txt
  src/startup.sh
  src/users/migrations/0001_initial.py
  src/users/models.py
  src/users/serializers.py
  src/users/tests.py
  src/users/tests/__init__.py
  src/users/tests/test_views.py
  src/users/urls.py
  src/users/views.py
  startup.sh
Labels: Atualização, DevOps, Sprint 10, Testes, backend, docker, enhancement, pull request, user-story

#119 #112/continuação testes unitario
  src/CheerUp/settings.py
  src/CheerUp/urls.py
  src/paciente/migrations/0002_auto_20210419_1825.py
  src/paciente/models.py
  src/paciente/serializers.py
  src/paciente/tests.py
  src/paciente/tests/__init__.py
  src/paciente/tests/test_views.py
  src/paciente/urls.py
  src/paciente/views.py
  src/requirements.txt
  src/users/admin.py
  src/users/apps.py
  src/users/serializers.py
  src/users/tests/test_views.py
  src/users/urls.py
  src/users/views.py
Labels: Atualização, DevOps, Sprint 10, Testes, backend

#125 DevOps_CD #122
  .github/workflows/CD.yml
Labels: DevOps

#133 Docs review sprint
  docs/sprints/results/result_spriint_10.md
Labels: ScrumMaster, documentation, pull request
